networks:
  main:
    name: main
    external: true

services:
  source:
    build:
      context: .
      args:
        - GITHUB_ACTOR
        - GITHUB_TOKEN
    image: cq-ynab-source:latest
    container_name: cq-ynab-source
    networks:
      - main
    command: serve
